services:
  api:
    image: atc-challenge:dev
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      ATC_BASE_URL: http://mock:4000
      REDIS_URL: redis://redis:6379
      CACHE_TTL_CLUBS: 3600
      CACHE_TTL_COURTS: 1800
      CACHE_TTL_SLOTS: 300
      # Rate Limiting Configuration
      RATE_LIMIT_RPM: 60
      RATE_LIMIT_BUCKET_TTL_SECONDS: 120
      RATE_LIMIT_MAX_WAIT_TIME_MS: 60000
      RATE_LIMIT_CHECK_INTERVAL_MS: 100
      RATE_LIMIT_STRATEGY: token_bucket
      CIRCUIT_BREAKER_THRESHOLD: 5
      CIRCUIT_BREAKER_TIMEOUT: 30000
  mock:
    image: atc-challenge:dev
    command: node /usr/src/app/mock/server.js
    volumes:
      - ./mock:/usr/src/app/mock
    ports:
      - 4000:4000
    environment:
      EVENT_INTERVAL_SECONDS: 10
      REQUESTS_PER_MINUTE: 60
      EVENT_PUBLISHER_URL: http://api:3000/events
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
volumes:
  redis_data:
